<?php

/**
 * @file
 * This file contains all install related hooks.
 */

/**
 * Implements hook_uninstall().
 */
function islandora_url_redirector_uninstall() {
  $variables = array(
    'islandora_url_redirector_path_snippet',
    'islandora_url_redirector_solr_field',
    'islandora_url_redirector_base',
    'islandora_url_redirector_solr_base',
  );
  array_walk($variables, 'variable_del');
}
