<?php

/**
 * Implements hook_menu().
 */
function islandora_identifier_lookup_menu() {
  $items = array();
  $items['islandora/idlookup/uuid/%'] = array(
    'access callback' => TRUE,
    'page callback' => 'islandora_identifier_lookup_lookup_id',
    'page arguments' => array(3),
    'delivery callback' => 'islandora_identifier_lookup_deliver_id',
    'type' => MENU_CALLBACK,
  );
  $items['islandora/idlookup/pid/%'] = array(
    'access callback' => TRUE,
    'page callback' => 'islandora_identifier_lookup_lookup_pid',
    'page arguments' => array(3),
    'delivery callback' => 'islandora_identifier_lookup_deliver_id',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function islandora_identifier_lookup_lookup_id($uuid) {
  $pid = islandora_identifier_lookup_get_pid($uuid);
  return trim($pid);
}

function islandora_identifier_lookup_lookup_pid($pid) {
  $object = islandora_object_load($pid);
  $mods_content = $object['MODS']->content;

  $dom = new DOMDocument();
  $dom->loadXML($mods_content);
  $xpath = new DOMXpath($dom);
  $xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
  $xpath_expression = '//mods:mods[1]/mods:identifier[@type="uuid"]';
  $uuids = $xpath->query($xpath_expression);
  return trim($uuids->item(0)->nodeValue);
}

function islandora_identifier_lookup_deliver_id($output) {
  drupal_add_http_header('Content-type', 'text/plain');
  drupal_add_http_header('Content-length', strlen($output));
  print $output;
  drupal_page_footer();
}

/**
 * Implements hook_islandora_datastream_alter().
 *
 * Adds an <identifier type="uuid"> element to all new MODS datastreams.
 */
function islandora_identifier_lookup_islandora_datastream_alter(AbstractObject &$object, AbstractDatastream &$datastream, &$context) {
  if ($context['action'] == 'ingest') {
    // Assumes MODS.
    if ($datastream->id == 'MODS') {

      $dom = new DOMDocument;
      $dom->loadXML($datastream->content);

      $identifiers = $dom->getElementsByTagName('identifier');

      // Build the <identifier> element we are adding.
      $type = $dom->createAttribute('type');
      $type->value = 'uuid';
      $uuid = `uuidgen`;
      $uuid_identifier = $dom->createElement('identifier', trim($uuid));
      $uuid_identifier->appendChild($type);

      // Figure out where to add it. If one ore more <identifier> elements
      // exist in the document, add the new one before the first existing one.
      if ($identifiers->length) {
        $dom->documentElement->insertBefore($uuid_identifier, $identifiers->item(0));
      }
      else {
        // If none exist, append it to the end of the document.
        $dom->documentElement->appendChild($uuid_identifier);
      }

      $updated_mods_xml = $dom->saveXML();
      $datastream->setContentFromString($updated_mods_xml);
    }
  }
}

/**
 * Performs a query to Islandora's Solr index to get a PID.
 *
 * @param string $uuid
 *   A UUID.
 */
function islandora_identifier_lookup_get_pid($uuid) {
  $solr_url = variable_get('islandora_solr_url', 'http://localhost:8080/solr');
  $target_element = 'mods_identifier_uuid_s';
  $pid_query = $solr_url . '/select?version=1.2&wt=json&json.nl=map&q=' .
    $target_element . ':' . '%22' . $uuid . '%22&fl=PID';
  $raw_result = drupal_http_request($pid_query);
  if ($raw_result->code != 200) {
    return FALSE;
  }
  $query_result = json_decode($raw_result->data);
  if ($query_result->response->numFound < 1) {
    return FALSE;
  }
  // If more than one object was found, take the PID of the first one.
  return $query_result->response->docs[0]->PID;
}
