<?php

/**
 * @file
 * The main islandora_identifier_lookup module file.
 */

/**
 * Implements hook_menu().
 */
function islandora_identifier_lookup_menu() {
  $items = array();
  $items['admin/islandora/tools/idlookup'] = array(
    'title' => 'Islandora Identifier Lookup',
    'description' => 'Configure Islandora Identifier Lookup.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_identifier_lookup_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['islandora/idlookup/uuid/%'] = array(
    'access callback' => TRUE,
    'page callback' => 'islandora_identifier_lookup_lookup_id',
    'page arguments' => array(3),
    'delivery callback' => 'islandora_identifier_lookup_deliver_id',
    'type' => MENU_CALLBACK,
  );
  $items['islandora/idlookup/pid/%'] = array(
    'access callback' => TRUE,
    'page callback' => 'islandora_identifier_lookup_lookup_pid',
    'page arguments' => array(3),
    'delivery callback' => 'islandora_identifier_lookup_deliver_id',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Admin settings form builder.
 */
function islandora_identifier_lookup_admin_settings() {
  $form['islandora_identifier_lookup_path_to_uuidgen'] = array(
    '#title' => t('Path to uuidgen'),
    '#type' => 'textfield',
    '#size' => 60,
    '#default_value' => variable_get('islandora_identifier_lookup_path_to_uuidgen', '/usr/bin/uuidgen'),
    '#description' => t('Full path to uuidgen or equivalent on your server.'),
    '#maxlength' => 255,
  );
  $form['islandora_identifier_lookup_pid_solr_field'] = array(
    '#type' => 'textfield',
    '#title' => t('UUID Solr field'),
    '#size' => 60,
    '#default_value' => variable_get('islandora_identifier_lookup_pid_solr_field', 'mods_identifier_uuid_s'),
    '#description' => t('Solr fieldname to use in queries to get PID corresponding to UUID.'),
    '#maxlength' => 255,
  );
  $form['islandora_identifier_lookup_add_uuids'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add identifier elements containing UUIDs to new objects'),
    '#default_value' => variable_get('islandora_identifier_lookup_add_uuids', 1),
    '#description' => t("Check this option if you want to add an &lt;idenfitier&gt;
      element (type='uuid') containing a UUID to each new object's MODS datastream."),
  );

  return system_settings_form($form);
}

/**
 * Given a UUID, returns the PID of the corresponding object.
 *
 * @param string $uuid
 *   A UUID.
 *
 * @return string|bool
 *   The object's PID or if the object doesn't exsit, FALSE.
 */
function islandora_identifier_lookup_lookup_id($uuid) {
  // Validate the UUID.
  if (preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i', trim($uuid))) {
    $pid = islandora_identifier_lookup_query_solr($uuid, 'UUID');
  }
  else {
    return FALSE;
  }
  return trim($pid);
}

/**
 * Given a PID, returns the UUID of the corresponding object.
 *
 * @param string $pid
 *   A PID.
 *
 * @return string|bool
 *   The object's UUID or if one can't be found, FALSE.
 */
function islandora_identifier_lookup_lookup_pid($pid) {
  // Validate PID. Cribbed from islandora/includes/utilities.inc (which we don't
  // load here since it is almost 1000 lines long.)
  if (!(drupal_strlen(trim($pid)) <= 64 && preg_match('/^([A-Za-z0-9]|-|\.)+:(([A-Za-z0-9])|-|\.|~|_|(%[0-9A-F]{2}))+$/', trim($pid)))) {
    return FALSE;
  }
  if (!$object = islandora_object_load($pid)) {
    return FALSE;
  }
  if (!isset($object['MODS'])) {
    return FALSE;
  }

  if ($uuid = islandora_identifier_lookup_query_solr($pid, 'PID')) {
    return trim($uuid);
  }
  else {
    return FALSE;
  }
}

/**
 * Page delivery callback.
 */
function islandora_identifier_lookup_deliver_id($output) {
  if (!$output) {
    drupal_add_http_header('Status', '404 Not Found');
  }
  else {
    drupal_add_http_header('Content-type', 'text/plain');
    drupal_add_http_header('Content-length', strlen($output));
    print $output;
  }
  drupal_page_footer();
}

/**
 * Implements hook_islandora_datastream_alter().
 *
 * Adds an <identifier type="uuid"> element to all new MODS datastreams.
 */
function islandora_identifier_lookup_islandora_datastream_alter(AbstractObject &$object, AbstractDatastream &$datastream, &$context) {
  if (variable_get('islandora_identifier_lookup_add_uuids', 1) && $context['action'] == 'ingest') {
    // Assumes MODS.
    if ($datastream->id == 'MODS') {
      $dom = new DOMDocument();
      $dom->loadXML($datastream->content);

      $identifiers = $dom->getElementsByTagName('identifier');

      // See if this MODS document already has an <identifier type="uuid">.
      $xpath = new DOMXpath($dom);
      $xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
      $xpath_expression = variable_get('islandora_identifier_lookup_uuid_xpath', '//mods:mods[1]/mods:identifier[@type="uuid"]');
      $uuids = $xpath->query($xpath_expression);

      if (!$uuids->length) {
        // Build the <identifier> element we are adding.
        $type = $dom->createAttribute('type');
        $type->value = 'uuid';
        $path_to_uuidgen = variable_get('islandora_identifier_lookup_path_to_uuidgen', '/usr/bin/uuidgen');
        $uuid = `$path_to_uuidgen`;
        $uuid_identifier = $dom->createElement('identifier', trim($uuid));
        $uuid_identifier->appendChild($type);

        // Figure out where to add it. If one ore more <identifier> elements
        // exist in the document, add the new one before the first existing one.
        if ($identifiers->length) {
          $dom->documentElement->insertBefore($uuid_identifier, $identifiers->item(0));
        }
        else {
          // If none exist, append it to the end of the document.
          $dom->documentElement->appendChild($uuid_identifier);
        }

        $updated_mods_xml = $dom->saveXML();
        $datastream->setContentFromString($updated_mods_xml);
      }
    }
  }
}

/**
 * Queries Islandora's Solr index.
 *
 * Given a PID, it queries for a UUID, and given a UUID,
 * it queries for a PID.
 *
 * @param string $input
 *   Either a UUID or a PID.
 * @param string $type
 *   What the $input is. Either 'UUID' or 'PID'.
 *
 * @return string|bool
 *   The retrieved PID or UUID, or, if none is found, FALSE.
 */
function islandora_identifier_lookup_query_solr($input, $type) {
  $solr_url = variable_get('islandora_solr_url', 'http://localhost:8080/solr');
  $uuid_element = variable_get('islandora_identifier_lookup_pid_solr_field', 'mods_identifier_uuid_s');

  if ($type == 'UUID') {
    $target_field = $uuid_element;
    $return_field = 'PID';
  }
  elseif ($type == 'PID') {
    $target_field = 'PID';
    $return_field = $uuid_element;
  }
  else {
    return FALSE;
  }

  $query = $solr_url . '/select?version=1.2&wt=json&json.nl=map&q=' .
    $target_field . ':%22' . $input . '%22&fl=' . $return_field;
  $raw_result = drupal_http_request($query);
  if ($raw_result->code != 200) {
    return FALSE;
  }
  $query_result = json_decode($raw_result->data);
  if ($query_result->response->numFound < 1) {
    return FALSE;
  }
  // The query should only find one object, but if it finds more than one,
  // take the first one.
  return $query_result->response->docs[0]->{$return_field};
}
